{% set name = "empty-files" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/empty-files-{{ version }}.tar.gz
  sha256: 22e74de327271ef9592a661aaa53bb1d5fa6cfd539dac7315625c8b30b7292ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - empty_files
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/approvals/EmptyFiles.Python
  summary: Serves empty files of many types
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
